name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pdf2image python-pptx python-docx PyPDF2

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --onefile --windowed read_pdf_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4   # <-- แก้จาก v3 เป็น v4
        with:
          name: macos-app
          path: dist/read_pdf_gui
